### ISSUE TITLE
typo in the jquery iterator pattern

### ISSUE THREAD

**Issue by adnasa** [addyosmani/essential-js-design-patterns#185]
Found a typo in the jquery iterator pattern example, with unnecessary extra quote in the log call.
PR coming up..

**Comment by abdulhannanali** [comment]
This issue can be closed now..

**Comment by abdulhannanali** [comment]
@addyosmani just closed an issue :clap: :sob: :sob: :sob: :+1: :heart: :raised_hands: :bowing_man: :bowing_woman:
