### ISSUE TITLE
JS example indentation error.

### ISSUE THREAD

**Issue by karlpatrickespiritu** [addyosmani/essential-js-design-patterns#192]
![indentation-error](https://cloud.githubusercontent.com/assets/10472504/11367310/bc4b511c-92ed-11e5-933d-d34a5e3fc1b4.png)

PR comming up.

**Comment by addyosmani** [comment]
Thank you once again, @karlpatrickespiritu! Landed back in https://github.com/addyosmani/essential-js-design-patterns/pull/193.
