### ISSUE TITLE
Dead repository link

### ISSUE THREAD

**Issue by Daniel-Hug** [addyosmani/essential-js-design-patterns#207]
Under the heading "Dependency declaration pattern", I read the following:

> Alternatively, a version of the jQuery $.extend() method extracted from core can be found here: https://github.com/addyosmani/jquery.parts.

The link to your jquery.parts repo is a 404.

**Comment by addyosmani** [comment]
Ah, I ended up sunsetting that repository 🤔. I should drop that reference from the book. Thanks again for all your helpful feedback, @Daniel-Hug!
